version: "3"
services:
  web:
    # Image location
    image: metabol/devops:pyapp
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.05"
          memory: 10M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet
networks:
  webnet:

